# Generated by Django 2.0.3 on 2018-06-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0003_auto_20180531_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confiteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('photo', models.ImageField(default='SOME STRING', upload_to='photos/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='funcion',
            options={'verbose_name': 'Funciones', 'verbose_name_plural': 'Funciones'},
        ),
    ]
