# Generated by Django 2.0.3 on 2018-06-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0004_auto_20180601_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='confiteria',
            name='precio',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
